# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/lthendral10/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [15]:
!git clone https://github.com/lthendral10/flyrank-ml-internship.git
%cd flyrank-ml-internship

Cloning into 'flyrank-ml-internship'...
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 139 (delta 49), reused 92 (delta 27), pack-reused 0 (from 0)
Receiving objects: 100% (139/139), 1.85 MiB | 16.95 MiB/s, done.
Resolving deltas: 100% (49/49), done.
/content/flyrank-ml-internship/flyrank-ml-internship

In [16]:
!find . -name "*.parquet"

In [17]:
!ls
!find . -maxdepth 3 -type f

AGENTS.md  DATA_USE.md	LICENSE    README.md	     SETUP.md	 work
CLAUDE.md  docs		notebooks  requirements.txt  skills
data	   GUIDE.md	outputs    scripts	     submission
./README.md
./data/raw/content_refresh_anonymized.csv
./skills/README.md
./skills/deploying-static-pages/SKILL.md
./skills/directing-your-ai-assistant/SKILL.md
./skills/auditing-signals/SKILL.md
./skills/writing-research-papers/SKILL.md
./skills/hunting-leakage-and-validating/SKILL.md
./skills/querying-big-datasets/SKILL.md
./skills/framing-ml-problems/SKILL.md
./skills/training-honest-models/SKILL.md
./skills/building-baselines/SKILL.md
./skills/writing-honest-claims/SKILL.md
./skills/writing-data-contracts/SKILL.md
./DATA_USE.md
./work/README.md
./work/notebooks/w04_signal_audit.ipynb
./work/notebooks/w07_action_playbook.ipynb
./work/notebooks/w03_data_contract.ipynb
./work/notebooks/w04_baseline_score.ipynb
./work/notebooks/capstone.ipynb
./work/notebooks/w05_model.ipynb
./work/notebooks/w01_research_question.ipynb
./work/notebooks/w03_feature_leakage_check.ipynb
./work/notebooks/w02_ml_task_framing.ipynb
./work/notebooks/w06_validation_audit.ipynb
./work/capstone_report_template.md
./.git/info/exclude
./.git/logs/HEAD
./.git/config
./.git/hooks/push-to-checkout.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/pre-push.sample
./.git/hooks/post-update.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/update.sample
./.git/hooks/pre-receive.sample
./.git/hooks/pre-commit.sample
./.git/hooks/commit-msg.sample
./.git/hooks/pre-rebase.sample
./.git/HEAD
./.git/index
./.git/description
./.git/packed-refs
./notebooks/01_first_look_and_discovery.ipynb
./notebooks/03_working_with_the_full_release.ipynb
./notebooks/02_your_first_readable_model.ipynb
./submission/README.md
./submission/paper_url.txt
./requirements.txt
./outputs/refresh_queue_sample.csv
./outputs/charts/action_mix.svg
./outputs/charts/confidence_mix.svg
./outputs/charts/trend_distribution.svg
./outputs/charts/top_reason_codes.svg
./outputs/charts/top_feature_importance.svg
./outputs/model_report.md
./.gitignore
./AGENTS.md
./GUIDE.md
./.github/workflows/personalize.yml
./.github/workflows/smoke-test.yml
./.github/workflows/data-path-smoke.yml
./scripts/01_prepare_features.py
./scripts/03_train_model.py
./scripts/04_evaluate_and_export.py
./scripts/02_baseline_score.py
./scripts/run_all.py
./scripts/ml_utils.py
./scripts/05_build_pdf_report.py
./docs/data-dictionary.md
./docs/flyrank-seo-research-march-2026.pdf
./docs/intern-free-tooling-guide.md
./docs/ml-intern-dataset-and-lane-guide.md
./docs/ml-core-foundation-framework.md
./SETUP.md
./CLAUDE.md
./LICENSE

In [18]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [19]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Unit of Analysis + Time Window

One row represents one content page. The dataset contains SEO, traffic, and engagement information for each page over the available reporting period. I will use this data to analyze content performance and identify pages that may require optimization

In [20]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

df.head()

Dataset Shape: (30000, 44)

Columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [21]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Fields: Feature / Label / Context / Excluded

### Features
- search_volume
- impressions_90d
- clicks_90d
- ctr
- avg_position

These features are available before making a content optimization decision and can be used as model inputs.

### Label (Target/Proxy)
- trend_direction

I use **trend_direction** as the target because it indicates whether a page's performance is improving, stable, or declining.

### Context
- content_id
- client_id
- content_type
- main_intent

These fields provide information about the content but are not the primary prediction target.

### Excluded
- ai_sessions_90d
- ai_traffic_pct

These fields are excluded because they are not essential for my current ML task and may not generalize well for predicting content performance.

In [22]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

features = [
    "search_volume",
    "impressions_90d",
    "clicks_90d",
    "ctr",
    "avg_position"
]

label = "trend_direction"

context = [
    "content_id",
    "client_id",
    "content_type",
    "main_intent"
]

excluded = [
    "ai_sessions_90d",
    "ai_traffic_pct"
]

print("Features:", features)
print("\nLabel:", label)
print("\nContext:", context)
print("\nExcluded:", excluded)

Features: ['search_volume', 'impressions_90d', 'clicks_90d', 'ctr', 'avg_position']

Label: trend_direction

Context: ['content_id', 'client_id', 'content_type', 'main_intent']

Excluded: ['ai_sessions_90d', 'ai_traffic_pct']

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [23]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Verify it with Queries

I verified that each row represents one content page. I also checked the dataset size and examined missing values in the features selected for my ML task. These checks help confirm that the data is suitable for analysis.

In [24]:
import pandas as pd

# Load dataset
df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

# Query 1: Verify grain
print("Unique content IDs:", df["content_id"].nunique())
print("Total rows:", len(df))

# Query 2: Dataset size
print("\nDataset Shape:", df.shape)

# Query 3: Missing values in selected features
features = [
    "search_volume",
    "impressions_90d",
    "clicks_90d",
    "ctr",
    "avg_position"
]

print("\nMissing Values:")
print(df[features].isnull().sum())

Unique content IDs: 30000
Total rows: 30000

Dataset Shape: (30000, 44)

Missing Values:
search_volume      2468
impressions_90d       0
clicks_90d            0
ctr                   0
avg_position          0
dtype: int64

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

In [25]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Data Limits

This dataset provides historical SEO and content performance information, but it cannot explain why search performance changes. External factors such as Google algorithm updates, competitor actions, seasonal trends, or marketing campaigns are not included. Therefore, the results should be used for decision support rather than as proof of cause and effect.

In [26]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

print("Total Rows:", len(df))
print("Total Columns:", len(df.columns))

print("\nColumns Used:")
print([
    "search_volume",
    "impressions_90d",
    "clicks_90d",
    "ctr",
    "avg_position",
    "trend_direction"
])

Total Rows: 30000
Total Columns: 44

Columns Used:
['search_volume', 'impressions_90d', 'clicks_90d', 'ctr', 'avg_position', 'trend_direction']

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.